### ISSUE TITLE
Integrate the zenpayroll on rails application

### ISSUE THREAD

**Issue by vishalyuvasoft** [ShiftDock/omniauth-zenpayroll#1]
Hello,

Any way to integrate zenpayroll on my  rails appliction.

and in this gem some conflicts at omniauth-zenpayroll/lib/omniauth/strategies/zenpayroll.rb so please resolved this first.

**Comment by JonMidhir** [comment]
Just fixed merge commits in b7a5e07b789e3a3e67e08dae1877bf2f15e0a734. Sorry about that.

Version 0.1.0 is available from Rubygems with the fix.

You'll need to talk to ZenPayroll about consuming their API, this is a third party gem.

**Comment by vishalyuvasoft** [comment]
Hello @JonMidhir 

Can you explain me how to i integrate the zenpayroll in my rails application.
Please help me!

**Comment by JonMidhir** [comment]
Hi @vishalyuvasoft 

I can't tell you how to do that because I don't work for ZenPayroll. You'll need to contact them to get the necessary login credentials.
